# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7058768db9c9ec250e8b605b59948f92fb7748a54081e18461bb8702470b37cd205fedbefd97d142737fd9f88267087bfb1ee47aa09e2168488a89f9105c2a1

test:
  secret_key_base: 412ad282477b38c12bf88c0b2904882eb9f26101c4b3905799dcb1569dcf9ccaee4c6fbbf63f2ff2eeecde7dbebff58b613f65d954ba79a41901c8528cc6b500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
